apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: e4szylqg8-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-0cca53af26.z3r1.p3.openshiftapps.com/rhtap/rhtap-qe:87ec1bc24dfd023b4aa10cc7cb971abbb52434f8@sha256:49e5faa453ff66deb9d1ad9b54772d7b1bd91a94c9050b8a6843838fb7367be7
          name: container-image
